### ISSUE TITLE
Invalid UTF-8

### ISSUE THREAD

**Issue by ptescher** [botandrose/sprockets-image_compressor#1] opened 2011-12-21 00:42 UTC
After adding sprockets-image_compressor to the gem file and running rake --trace assets:precompile we get this error:

<asset filename> has a invalid UTF-8 byte sequence
sprockets-2.0.3/lib/sprockets/utils.rb:18:in `block in read_unicode'

**Comment by botandrose** [comment] 2011-12-24 00:26
Hmm. Are you on Ruby 1.9?

**Comment by ptescher** [comment] 2011-12-25 00:30
Yes, 1.9.3-p0

**Comment by botandrose** [comment] 2011-12-26 22:34
@pat2man I've been able to reproduce the issue, and unsurprisingly, its related to encodings in 1.9. Trying to make a fix now.

**Comment by botandrose** [comment] 2011-12-26 23:34
@pat2man Looks like this is a problem with sprockets itself. If the asset has any processors, sprockets will open it as unicode, rather than binary. Not a problem in 1.8, problem in 1.9.

Opened an issue with sprockets: https://github.com/sstephenson/sprockets/issues/269

**Comment by ptescher** [comment] 2011-12-27 00:48
Awesome, thanks for figuring this out!

**Comment by botandrose** [comment] 2011-12-31 22:44
@pat2man Got a pull request on sprockets that looks like it will be merged in for the 2.2.0 release. In the meantime, you can use my fork, if you like: https://github.com/botandrose/sprockets/tree/automatic_binary_encoding

**Comment by botandrose** [comment] 2012-01-10 19:17
@pat2man Sprockets 2.2.0 was just released! Closing this issue. Reopen if you still have problems.

**Closed as completed by botandrose** 2012-01-10 19:17 UTC
