### ISSUE TITLE
Doesn't seem to be working on Rails 3.2.8

### ISSUE THREAD

**Issue by ndbroadbent** [botandrose/sprockets-image_compressor#6] opened 2012-09-22 13:49 UTC
I've added `gem 'sprockets-image_compressor'` to my Gemfile, and have run `rake assets:precompile`.

However, the images don't seem to be compressed using `pngcrush`. I've installed the `pngcrush` package on Ubuntu 12.04, and the `pngcrush` version is `1.7.9`.

I can tell they are not being compressed because I ran `pngcrush` manually on an image, and recorded the size of the output file (which was `39286`). However, the size of the image in `public/assets` is the same as the original, at `39359`.

My `Gemfile.lock` has:
- `sprockets` -> `2.1.3`
- `sprockets-image_compressor` -> `0.2.0`

Please let me know if you need any further information.

**Comment by botandrose** [comment] 2012-09-23 02:28
Can you post a copy of the offending .png so I can reproduce?

**Comment by botandrose** [comment] 2013-03-17 19:11
@ndbroadbent closing... feel free to reopen if you're still having issues with this. ps, thanks for turbo-sprockets-rails3!

**Closed as completed by botandrose** 2013-03-17 19:11 UTC

**Comment by tomchentw** [comment] 2014-11-21 09:55
Same issue +1

``` rb
rails 3.2.18
sprockets 2.2.3
sprockets-image_compressor 0.3.0
```

**Comment by tomchentw** [comment] 2014-11-21 09:58
I think the cause might be related to this commit 8ced999649c5abbb5ca45c9966646b18248b777d.
It's using `::Rails::Engine` in Rails < 4.

However, since this gem targets Rails >= 3.1, I believe it's safe to use `::Rails::Railtie` directly since it has been introduced by 3.0: http://apidock.com/rails/v3.0.0/Rails/Railtie

**Comment by tomchentw** [comment] 2014-11-21 10:18
Forked and tried with no luck ... :(
