### ISSUE TITLE
Errno::EPERM: Operation not permitted

### ISSUE THREAD

**Issue by forsberg1** [botandrose/sprockets-image_compressor#10] opened 2013-08-29 10:12 UTC
Dont know if this is a issue or not but took me some time to figure this out.

If you have the gem installed and use Rails.cache.clear you get permission issues on tmp folder.

Remove the gem  will clear the error.

**Comment by botandrose** [comment] 2014-05-18 21:44
Doing some issue cleanup here.

Can't reproduce, closing. Feel free to reopen with a minimal reproducible test case.

**Closed as completed by botandrose** 2014-05-18 21:44 UTC
