### ISSUE TITLE
Sprockets complains of invalid byte sequence for image file when precompiling

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [botandrose/sprockets-image_compressor#16] opened 2014-05-15 19:23 UTC
It doesn't make sense to me because a jpg is a binary file, no? This error crops up when both `sprockets-image_compressor` and `sprockets-webp` are installed. When one or the other is commented out, this error doesn't exist. Perhaps one or both gems return an incorrect value in the post processor?

Image: ![email-footer_bg](https://cloud.githubusercontent.com/assets/6055027/2989633/4e9d0a28-dc66-11e3-8bc7-9ec265ad9baa.jpg)

``` ruby
Encoding::InvalidByteSequenceError: /home/jake/ror/dev.website/app/assets/images/emails/email-footer_bg.jpg is not valid UTF-8
  (in /home/jake/ror/dev.website/app/assets/images/emails/email-footer_bg.jpg)
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/tilt-1.4.1/lib/tilt/template.rb:75:in `initialize'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/context.rb:196:in `new'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/context.rb:196:in `block in evaluate'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:12:in `initialize'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `new'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `block in build_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:373:in `build_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:16:in `initialize'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `new'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `build_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:61:in `block (3 levels) in define'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/jake/.rvm/gems/ruby-2.1.0@website/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:60:in `block (2 levels) in define'
/home/jake/.rvm/gems/ruby-2.1.0@global/bin/ruby_executable_hooks:15:in `eval'
/home/jake/.rvm/gems/ruby-2.1.0@global/bin/ruby_executable_hooks:15:in `<main>'

```

Addendum: I noticed Sprockets is calling processed_asset instead of static_asset (which is normal for images)...is this expected? It's as if Sprockets is trying to read the file as if it were JS or CSS.

**Comment by botandrose** [comment] 2014-05-18 21:34
@JakeTheSnake3p0 I set up a minimal app here to try to reproduce: https://github.com/botandrose/sprockets-test

No luck reproducing... invoking `rake` will reliably generate both the compressed jpg and the webp version, so I think the issue is something outside of rails, sprockets-image_compressor, and sprockets-webp. I'm going to close this issue, but if you can provide a minimal test case to reproduce the error, feel free to reopen this, and I'll take another look.

**Closed as completed by botandrose** 2014-05-18 21:34 UTC

**Comment by JakeTheSnake3p0** [comment] 2014-05-19 00:21
I honestly can't say why it doesn't happen on anyone else's project much less a new one, but I think I narrowed down the issue. I noticed that my png and other file types were compressing just fine, it was only jpg files that were screwing up. I reinstalled jpegoptim thinking it had something to do with that, but no. I looked closer at your code and your jpg compressor class reads the file differently from your png compressor class.

I figure it had something to do with the fact that the file contents weren't being returned (read) in binary mode. I pushed a fix to my clone of your repo. I've never done a merge with another git repo before, but you can see what I've done to fix the issue. I used the method illustrated [here](http://techblog.leosoto.com/reading-binary-file-on-ruby/).

On a side note, what purpose does the `out =` variable serve in those classes?

https://github.com/JakeTheSnake3p0/sprockets-image_compressor

**Comment by botandrose** [comment] 2014-05-19 00:31
Looks good! All the tests pass after this change? If so, turn your fork into a pull request, and I'll merge it.

**Comment by JakeTheSnake3p0** [comment] 2014-05-19 00:43
All tests passed; pull request sent.
